name: Build macOS Installer

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    # The type of runner that the job will run on (e.g. macOS, win, linux)
    runs-on: macos-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: temurin
#      - name: Cache Maven packages
#        uses: actions/cache@v2
#        with:
#          path: ~/.m2
#          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
#          restore-keys: ${{ runner.os }}-m2
      # execute the actual maven step that will call jpackage and create the installer          
      - name: Build with Maven
        run: mvn -B clean package jpackage:jpackage -f rotp-public/pom.xml
      #- name: Update Automatic Release
      #  uses: marvinpinto/action-automatic-releases@latest
      #  with:
      #    repo_token: "${{ secrets.GITHUB_TOKEN}}"
      #    automatic_release_tag: "macOS-latest"
      #    prerelease: true
      #    title: "macOS Development Build"
      #    files: ./target/*.dmg
